// <auto-generated />
namespace GameFeed.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GameCompanyRoleasPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameCompanyRoleasPK));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091839246_GameCompany Role as PK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
